import {parseLink, downloadURL} from './core.js';
import {request, readLimited, resolveDownload} from './network.js';

const initial = {items:[], paused:true};
let state;
let chain = Promise.resolve();
let pumping = false;
const loaded = chrome.storage.local.get('batch').then(async ({batch}) => {
  state = batch || initial;
  // A worker can stop while probing or between creating and recording a download.
  // Never automatically restart an uncertain download: avoid duplicate files.
  for (const item of state.items) if (item.status === 'preparing') {
    item.status = 'action';item.message = 'Kiểm tra bị gián đoạn. Xem danh sách tải Chrome trước khi thử lại.';
  }
  await chrome.storage.local.set({batch:state});
});
function change(fn) {
  const task = chain.then(async () => {await loaded;const value = fn(state);await chrome.storage.local.set({batch:state});return value;});
  chain = task.catch(() => {});
  return task;
}
async function snapshot() {await loaded;await chain;return structuredClone(state);}
async function update(id, fields) {return change(s => {const item=s.items.find(i=>i.id===id);if(item)Object.assign(item,fields);});}

async function inspect(item) {
  let actual={...item};
  // A /file/d link can refer to a Workspace document. Resolve the official page first.
  if(item.type==='file') {
    try {
      const preview=await request(item.url,'include');
      let detected;
      try {detected=parseLink(preview.finalUrl);}catch{}
      if(detected?.id===item.id && detected.type!=='file') actual={...actual,type:detected.type};
      if(actual.type==='file' && preview.body) {
        const match=preview.body.match(/https:\/\/docs\.google\.com\/(document|spreadsheets|presentation)\/d\/([\w-]+)/);
        if(match?.[2]===item.id)actual.type=match[1];
      }
    }catch{/* The download endpoint still provides a useful independent check. */}
  }
  if(actual.type==='folder')return {status:'action',type:'folder',message:'Đây là thư mục. Quét và chọn các file bên trong.'};
  const url=downloadURL(actual);
  let result;
  try {result=await resolveDownload(url,'omit',actual);} catch {result={status:'error'};}
  let access='public';
  if(result.status!=='ready') {result=await resolveDownload(url,'include',actual);access='session';}
  return {status:result.status,type:actual.type,
    ...(result.name ? {name:result.name.trim()} : {}),
    message:result.status==='ready' ? (access==='public'?'Tải được không cần đăng nhập':'Tải được với phiên Google hiện tại') : result.message,
    access:result.status==='ready'?access:'unknown', downloadUrl:result.downloadUrl||url, confirmed:!!result.confirmed};
}

async function reconcile() {
  const current=await snapshot();
  for(const item of current.items.filter(i=>i.status==='downloading' && Number.isInteger(i.downloadId))) {
    const [download]=await chrome.downloads.search({id:item.downloadId});
    if(!download) {await update(item.id,{status:'action',message:'Không còn thông tin lượt tải trong Chrome. Kiểm tra trước khi thử lại.'});continue;}
    const suspicious=/text\/html|application\/xhtml/i.test(download.mime) && !/\.html?$/i.test(item.name);
    if(suspicious) {
      if(download.state==='in_progress')await chrome.downloads.cancel(download.id).catch(()=>{});
      // Remove only the file generated by this extension's tracked download.
      if(download.state==='complete')await chrome.downloads.removeFile(download.id).catch(()=>{});
      await update(item.id,{status:'action',message:'Google trả trang HTML thay vì file. Mở trên Google rồi thử lại.'});
    } else if(download.state==='complete')await update(item.id,{status:'done',message:'Đã tải xong',filename:download.filename});
    else if(download.state==='interrupted')await update(item.id,{status:'error',message:`Tải bị ngắt: ${download.error || 'không rõ nguyên nhân'}`});
  }
}
async function pump() {
  if(pumping)return;pumping=true;
  try {
    await reconcile();
    while(true) {
      const current=await snapshot();
      if(current.paused || current.items.filter(i=>i.status==='downloading').length>=2)break;
      const item=current.items.find(i=>i.status==='queued');if(!item)break;
      await update(item.id,{status:'preparing',message:'Đang kiểm tra khả năng tải…'});
      try {
        const info=await inspect(item);
        await update(item.id,info);
        if(info.status!=='ready' || item.mode==='check' || (await snapshot()).paused)continue;
        await update(item.id,{status:'preparing',message:'Đang bắt đầu tải…'});
        const options={url:info.downloadUrl,saveAs:false,conflictAction:'uniquify'};
        // Let Google/Chrome determine the extension and original filename.
        const id=await chrome.downloads.download(options);
        await update(item.id,{status:'downloading',downloadId:id,message:'Đang tải bằng Chrome…'});
        await reconcile();
      }catch(e) {await update(item.id,{status:'error',message:e.name==='AbortError'?'Google phản hồi quá chậm. Hãy thử lại.':e instanceof TypeError?'Chưa kiểm tra được: lỗi mạng hoặc Google yêu cầu đăng nhập. Mở Google để kiểm tra rồi thử lại.':`Không tải được: ${e.message}`});}
    }
  }finally {pumping=false;}
}

chrome.alarms.create('batch-tick',{periodInMinutes:0.5});
chrome.alarms.onAlarm.addListener(()=>{pump().catch(console.error);});
chrome.downloads.onChanged.addListener(()=>{pump().catch(console.error);});
chrome.runtime.onMessage.addListener((message,sender,respond)=>{
  if(sender.id!==chrome.runtime.id || !sender.url?.startsWith(chrome.runtime.getURL('')))return;
  handle(message).then(respond,e=>respond({error:e.message}));return true;
});
async function handle(message) {
  if(message.type==='get') {await reconcile();return snapshot();}
  if(message.type==='add') {
    await change(s=>{for(const input of message.items){const item=parseLink(input.url);if(!s.items.some(i=>i.id===item.id))s.items.push({...item,name:typeof input.name==='string'?input.name.slice(0,500):item.name,parent:input.parent||''});}});
    return snapshot();
  }
  if(message.type==='select') {await change(s=>{for(const i of s.items)if(message.ids.includes(i.id)&&i.type!=='folder')i.selected=message.selected;});return snapshot();}
  if(message.type==='queue') {
    await change(s=>{s.paused=false;for(const i of s.items)if(message.ids.includes(i.id)&&i.type!=='folder'&&!['preparing','downloading','queued','done'].includes(i.status)){i.status='queued';i.mode=message.mode==='check'?'check':'download';i.message='Đang chờ';}});
    void pump();return snapshot();
  }
  if(message.type==='stop') {await change(s=>{s.paused=true;for(const i of s.items)if(i.status==='queued'){i.status='new';i.message='Đã dừng hàng đợi';}});return snapshot();}
  if(message.type==='clear') {await change(s=>{s.items=s.items.filter(i=>['preparing','downloading','queued'].includes(i.status));});return snapshot();}
  if(message.type==='open') {
    const item=parseLink(message.url);await chrome.tabs.create({url:item.url});return {ok:true};
  }
  if(message.type==='folderHTML') {
    const item=parseLink(message.url);if(item.type!=='folder')throw new Error('Không phải thư mục.');
    const url=new URL('https://drive.google.com/embeddedfolderview');url.searchParams.set('id',item.id);
    if(item.resourceKey)url.searchParams.set('resourcekey',item.resourceKey);
    const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);
    try {const r=await fetch(url,{credentials:'include',signal:controller.signal});if(!r.ok)throw new Error(`Google trả HTTP ${r.status}. Mở thư mục trên Drive để kiểm tra quyền.`);return {html:await readLimited(r,2000000)};}
    finally {clearTimeout(timer);}
  }
  if(message.type==='scanTab') {
    const folder=parseLink(message.url);if(folder.type!=='folder')throw new Error('Không phải thư mục.');
    const tabs=await chrome.tabs.query({url:'https://drive.google.com/*'});
    const tab=tabs.find(t=>{try{return parseLink(t.url).id===folder.id;}catch{return false;}});
    if(!tab)throw new Error('Hãy mở thư mục trên Drive, chờ danh sách hiện ra rồi bấm “Quét tab Drive”.');
    const results=await chrome.scripting.executeScript({target:{tabId:tab.id},func:collectVisibleDriveItems});
    return {items:results[0]?.result||[]};
  }
  throw new Error('Lệnh không hợp lệ.');
}

// Reads only currently rendered entries. No guessed completeness, no hidden API tokens.
function collectVisibleDriveItems() {
  const found=new Map();
  for(const el of document.querySelectorAll('[data-id]')) {
    const id=el.getAttribute('data-id');
    if(!/^[\w-]{10,}$/.test(id)||!el.getClientRects().length)continue;
    if(!el.matches('[role="row"], [role="gridcell"], [role="listitem"]')&&!el.querySelector('[role="gridcell"]'))continue;
    const img=el.querySelector('img');
    const hints=[el.getAttribute('data-mime-type'),img?.src,img?.alt].filter(Boolean).join(' ');
    let type='file';
    if(/folder|thư mục/i.test(hints))type='folder';
    else if(/vnd.google-apps.document|Google Docs|Google Tài liệu/i.test(hints))type='document';
    else if(/vnd.google-apps.spreadsheet|Google Sheets|Google Trang tính/i.test(hints))type='spreadsheets';
    else if(/vnd.google-apps.presentation|Google Slides|Google Trang trình bày/i.test(hints))type='presentation';
    const name=el.querySelector('[data-tooltip]')?.getAttribute('data-tooltip')||el.querySelector('[data-column-field="name"]')?.textContent||el.getAttribute('aria-label')||id;
    const url=type==='folder'?`https://drive.google.com/drive/folders/${id}`:type==='file'?`https://drive.google.com/file/d/${id}/view`:`https://docs.google.com/${type}/d/${id}/edit`;
    found.set(id,{url,name:name.trim()});
  }
  return [...found.values()];
}
